version: '3.1'
services:
  sql:
    image: mysql:8.0
    restart: always
    volumes:
      - ./data/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
    ports:
      - 3306:3306